using T3.Web.Services.Match;

namespace T3.Web.Services.Commit;

public record CommitHeader
{
    /// <summary>
    /// The id of the commit. This is a unique id that is generated by the client.
    /// </summary>
    public required CommitId CommitId { get; init; }
    
    /// <summary>
    /// The id of the match that this commit belongs to.
    /// </summary>
    public required MatchId MatchId { get; init; }
    
    /// <summary>
    /// The id of the previous commit. This is used to create a linked list of commits.
    /// Multiple commits can point to the same previous commit.
    /// </summary>
    public CommitId? PreviousCommitId { get; init; }
    
    /// <summary>
    /// The author of the commit. Followers can follow a user or a session to see all the changes that happen in it.
    /// </summary>
    public required Author Author { get; init; }
    
    /// <summary>
    /// When the commit was created according to the client.
    /// </summary>
    public required Timestamp.Timestamp CreatedAt { get; init; }
}