import {CommitId, SetId} from "./typed-ids";
import {Timestamp} from "./timestamp";
import {SetCommitAuthor} from "./set-commit-author";

export interface SetCommitHeader {
  /// <summary>
  /// The id of the commit. This is a unique id that is generated by the client.
  /// </summary>
  commitId: CommitId;

  /// <summary>
  /// The id of set that this commit belongs to.
  /// </summary>
  setId: SetId;

  /// <summary>
  /// The id of the previous commit. This is used to create a linked list of commits.
  /// Multiple commits can point to the same previous commit.
  /// </summary>
  previousCommitId?: CommitId;

  /// <summary>
  /// The author of the commit. Followers can follow a user or a session to see all the changes that happen in it.
  /// </summary>
  author: SetCommitAuthor;

  /// <summary>
  /// When the commit was created according to the client.
  /// </summary>
  createdAt: Timestamp;
}
